### ISSUE TITLE
How to fetch for all versions + architectures?

### ISSUE THREAD

**Issue by jvolkman** [ziglang/fetch-them-macos-headers#17]
Instructions in https://github.com/ziglang/zig/pull/14185 were to add missing files here and submit a PR. Are there any tips for how to populate the six separate version+architecture variants? When I run `fetch` on my M1 mac, it just  `aarch-macos.12-none`.

Do I just copy the changes to the other directories, or do I need to run on all six combinations somehow?

**Comment by andrewrk** [comment]
All you need to do is add the missing include. Then the zig core team members, who, strategically, collectively, have macs that span the whole version and architecture range, do the fetching.

**Comment by jvolkman** [comment]
Got it. Thanks!
