### ISSUE TITLE
Add paths.h on macos

### ISSUE THREAD

**Issue by plajjan** [ziglang/fetch-them-macos-headers#24]
I saw sys/paths.h was added recently (https://github.com/ziglang/zig/pull/15951). I would like to have just paths.h!

FWIW, I'm slowly converting external library dependencies of Acton https://github.com/actonlang/acton/ to be compiled using zig cc rather than the system compiler, so slowly noticing what I'm missing.

**Comment by kubkon** [comment]
Done in 2db9f76d4c6b70670f2f11d44600bf96a2cec441
